name: Build website and publish

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Switch to gh-pages branch
              run: |
                  git config user.name "robalaban"
                  git config user.email "${{ secrets.GH_MAIL }}"
                  git remote add gh-token "https://${{ secrets.GITHUB_TOKEN}}@github.com/${{ github.repository }}.git"
                  git fetch gh-token
                  git checkout gh-pages 2>/dev/null || git checkout -b gh-pages
            - name: Set up Node
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: Install dependencies and build
              run: |
                  npm install
                  npm run build --if-present
            - name: Clean branch and push
              run: |
                  shopt -s extglob
                  rm -r !("build"|"CNAME")
                  git add .
                  git commit -m 'Updating website'
                  git push gh-token gh-pages
